# $Id: run2.mac 83851 2014-09-19 10:12:12Z gcosmo $
#
#

/run/initialize

/mydet/SelectDetector Torus
#/mydet/SelectDetector Box
#/mydet/SelectDetector Sphere
#/mydet/SelectDetector Tubs
#/mydet/SelectDetector Orb
#/mydet/SelectDetector Cons
#/mydet/SelectDetector TwistedTubs 
#/mydet/SelectDetector  TwistedBox
#/mydet/SelectDetector TwistedTrd
#/mydet/SelectDetector  TwistedTrap
#/mydet/SelectDetector TwistedTrap2
#/mydet/SelectDetector TwistedTrap3


/run/beamOn 10
